server: 
port: 9002 
spring: 
application: 
name: hrm-course 
datasource: 
driver-class-name: com.mysql.jdbc.Driver 
url: jdbc:mysql://localhost:3306/hrm_course 
username: root 
password: 111111 
mybatis-plus: 
mapper-locations: classpath:com/zxd/hrm/mapper/*Mapper.xml 
type-aliases-package: com.zxd.hrm.domain,com.zxd.hrm.query