spring:
  profiles:
    active: dev
  cloud:
    config:
      #uri: http://localhost:8848 #配置configserver单个服务器
      discovery:
        enabled: true
        service-id: config-server # 从Eureka通过服务名获取多个配置服务
      label: master #分支
      name: application-course #那个文件
      profile: ${spring.profiles.active} # 那个环境